# Generated by Django 5.0.11 on 2025-01-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AI', max_length=50, null=True)),
                ('nombre_producto', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AI', max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('numero_factura', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AI', max_length=50, null=True)),
            ],
            options={
                'db_table': 'FACTURAS',
                'managed': True,
            },
        ),
    ]
